EquiTimeProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepageapp.urls')),
    path('', include('scheduleapp.urls')),
    path('', include('noticeboardapp.urls')),
    path('', include('reminderapp.urls')),
    path('', include('competitionapp.urls')),
]

homepageapp/urls.py
from django.urls import path
from . import views

app_name = 'homepageapp'

urlpatterns = [
    path('', views.home_view, name='home-view'),
    path('register/', views.register_view, name='register-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('signin/', views.login_view, name='login-view'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('index/', views.index_view, name='index-view'),

]

noticeboardapp/urls.py
from django.urls import path

from . import views

app_name = 'noticeboardapp'

urlpatterns = [
    # C
    path('add-notice/', views.add_notice_view, name='add-notice-view'),

    # R
    path('noticeboard/', views.noticeboard_view, name='noticeboard-view'),

    # U
    path('<str:notice_title>/<int:notice_id>/update/', views.update_notice_view, name='update-notice-view'),

    # D
    path('<str:notice_title>/<int:notice_id>/delete/', views.delete_notice_view, name='delete-notice-view'),
    path('delete-notices/', views.delete_all_notices, name='delete-all-notices'),

]

noticeboardapp/models.py
from django.db import models


# Create your models here.

class Notice(models.Model):

    title = models.CharField(max_length=50, default='Notice')
    user = models.CharField(max_length=50, default='Guest')
    content = models.TextField(max_length=1000)
    timestamp = models.DateTimeField(auto_now_add=True)

noticeboardapp/views.py
from django.shortcuts import render, redirect
from datetime import date, datetime
from noticeboardapp.models import Notice
from django.contrib.auth.decorators import login_required



# Create your views here.


@login_required
def add_notice_view(request):


    if request.method == "GET":

        today = date.today()
        current_day = today.strftime("%A")

        return render(
            request,
            'noticeboard/add_notice.html',
            context={
                'today': today,
                'current_day': current_day,
            }
        )

    if request.method == "POST":

        title = request.POST.get('title')
        notice = request.POST.get('notice')
        current_user = request.user
        timestamp = datetime.now()

        if notice:
            Notice.objects.create(content=notice, timestamp=timestamp, title=title, user=current_user)

            notices = Notice.objects.all().order_by('-timestamp')
            today = date.today()
            current_day = today.strftime("%A")

            return render(
                request,
                'noticeboard/board.html',
                context={
                    'notices': notices,
                    'today': today,
                    'current_day': current_day,
                    'current_user': current_user,
                }
            )

        return redirect('noticeboardapp:noticeboard-view')


@login_required
def noticeboard_view(request):

    notices = Notice.objects.all().order_by('-timestamp')
    current_user = request.user
    today = date.today()
    current_day = today.strftime("%A")

    if request.method == "GET":

        if request.user.is_authenticated:

            return render(
                request,
                'noticeboard/board.html',
                context={
                    'notices': notices,
                    'today': today,
                    'current_day': current_day,
                    'current_user': current_user,
                }
            )

        else:
            return redirect('homepageapp:login-view')



@login_required
def update_notice_view(request, notice_title, notice_id):

    notice = Notice.objects.get(title=notice_title, id=notice_id)

    if request.method == "GET":
        return render(
            request,
            'noticeboard/update_notice.html',
            context={
                'notice': notice,
            }
        )

    if request.method == "POST":
        new_notice_title = request.POST.get('title')
        new_notice_content = request.POST.get('content')

        if new_notice_title:
            notice.title = new_notice_title
            notice.save()

        if new_notice_content:
            notice.content = new_notice_content
            notice.save()

        return redirect('noticeboardapp:noticeboard-view')


@login_required
def delete_notice_view(request, notice_title, notice_id):

    notice = Notice.objects.get(title=notice_title, id=notice_id)

    if request.method == "GET":

        return render(
            request,
            'noticeboard/delete_notice.html',
            context={
                'notice': notice,
            }
        )

    if request.method == "POST":
        notice.delete()

        return redirect('noticeboardapp:noticeboard-view')


@login_required
def delete_all_notices(request):

    notices = Notice.objects.all()

    if request.method == "POST":
        if notices and request.user.is_staff:
            notices.delete()
        else:
            return render(
                request,
                'noticeboard/no_permission_to_delete_all_notices.html',
            )

        return redirect('noticeboardapp:noticeboard-view')



    if request.method == "GET":
        return render(
            request,
            'noticeboard/delete_all_notices.html',
        )

noticeboardapp/templates/noticeboard/add_notice.html
{% extends 'homepageapp/base_2.html' %}
{% load static %}
{% load tz %}

{% block content %}

<style>
.notices {
    font-size: 20px;
    color:dimgrey;}
</style>

    <div class="container-fluid page-header">
    <div class="container">

    <div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Noticeboard</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
    <p class="notices">Title:</p>
    <input type="text" name="title" placeholder="Add new notice title">
    <br>
    <br>
    <p class="notices">Notice:</p>
    <textarea name="notice" placeholder="Add new notice" rows="5" cols="50"></textarea>
    <br>
    <br>
    <p><a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="submit" class="btn btn-info">Submit</button></a></p>
    <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" class="btn btn-info">Back</button></a>

</form>

        </div>
    </div>

{% endblock %}

noticeboardapp/templates/noticeboard/board.html
{% extends 'homepageapp/base_2.html' %}

{% load static %}
{% load tz %}

{% block content %}

    <div class="container-fluid page-header">
        <div class="container">

<div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Noticeboard</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>

    <a href="{% url 'noticeboardapp:add-notice-view' %}"><button class="btn btn-success">Add notice</button>
    <a href="{% url 'noticeboardapp:delete-all-notices' %}"><button class="btn btn-info">Delete all notices</button></a>

        <h3 style="color:dimgrey;">All notices:</h3>


        {% for notice in notices %}
        <div style="background:#e6e6fa !important" class="jumbotron text-left">
        <p><small>Added by: {{ notice.user }}</small></p>
        <p><small>Added on: {{ notice.timestamp }}</small></p>
        <p><i>{{ notice.title }}</i></p>
        <br>
        <p>{{ notice.content }}</p>
        <br>
            {% if user.username == notice.user or user.is_staff %}
                <a href="{% url 'noticeboardapp:delete-notice-view' notice.title notice.id %}"><button type="submit">Delete</button></a>
                <a href="{% url 'noticeboardapp:update-notice-view' notice.title notice.id %}"><button type="submit">Update</button></a>
            {% endif %}
        </div>
        {% endfor %}


        </div>
    </div>

{% endblock %}

noticeboardapp/templates/noticeboard/delete_all_notices.html
{% extends 'homepageapp/base.html' %}

{% block content %}
  <h4 style="color:red;">Do you really want to delete all notices?</h4>

    <form method="post">{% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-info">
      <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" class="btn btn-info">Back</button></a>

    </form>


{% endblock %}

noticeboardapp/templates/noticeboard/delete_notice.html
{% extends 'homepageapp/base.html' %}

{% block content %}

 <p><i>Do you want to delete this notice: '{{ notice.title }}'?</i></p>
  <form method="POST">{% csrf_token %}
    <input type="submit" value="Confirm" class="btn btn-info">
        <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" class="btn btn-info">Back</button></a>

  </form>

{% endblock %}

noticeboardapp/templates/noticeboard/no_permission_to_delete_all_notices.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h4 style="color:red;">No permission...</h4>
    <h4>Only the administrator can delete all notices.</h4>
    <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" class="btn btn-info">Back</button></a>


{% endblock %}

noticeboardapp/templates/noticeboard/update_notice.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <form method="POST">{% csrf_token %}
        <p><input type="text" name="title" value="{{ notice.title }}"></p>
        <textarea name="content" rows="5" cols="50">{{ notice.content }}</textarea>

        <p><input type="submit" value="Update" class="btn btn-info"></p>
        <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" class="btn btn-info">Back</button></a>

    </form>


{% endblock %}