EquiTimeProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepageapp.urls')),
    path('', include('scheduleapp.urls')),
    path('', include('noticeboardapp.urls')),
    path('', include('reminderapp.urls')),
    path('', include('competitionapp.urls')),
]

homepageapp/urls.py
from django.urls import path
from . import views

app_name = 'homepageapp'

urlpatterns = [
    path('', views.home_view, name='home-view'),
    path('register/', views.register_view, name='register-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('signin/', views.login_view, name='login-view'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('index/', views.index_view, name='index-view'),

]

reminderapp/urls.py
from django.urls import path
from . import views

app_name = 'reminderapp'

urlpatterns = [

    # C
    path('add-event/', views.add_event_view, name='add-event-view'),

    # R
    path('events/', views.all_events_view, name='all-events-view'),
    path('<int:event_id>/event/', views.event_detail_view, name='event-detail-view'),

    # U
    path('<int:event_id>/event/update/', views.event_update_view, name='event-update-view'),

    # D
    path('<int:event_id>/event/delete/', views.event_delete_view, name='event-delete-view'),

    ]

reminderapp/models.py
from django.db import models

# Create your models here.


class Event(models.Model):

    user = models.CharField(max_length=50, default='Guest')
    event_name = models.CharField(max_length=100)
    event_date = models.CharField(max_length=50, default='2023-01-01')
    event_time = models.CharField(max_length=50, default='12:00')
    reminder_date = models.CharField(max_length=50, default='2023-01-01')
    reminder_time = models.CharField(max_length=50, default='12:00')

reminderapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from datetime import date, datetime, time
from django_celery_beat.models import CrontabSchedule, PeriodicTask
from reminderapp.models import Event
from reminderapp.tasks import send_reminder_mail_func
from django.conf import settings
import json
from django.contrib.auth.decorators import login_required



# Create your views here.

@login_required
def add_event_view(request):

    if request.method == "GET":
        return render(
            request,
            'reminderapp/add_event.html'
        )

    if request.method == "POST":

        current_user = request.user
        event = request.POST.get('event')

        if event:
            Event.objects.create(event_name=event, user=current_user)

        return redirect('reminderapp:all-events-view')


@login_required
def all_events_view(request):

    events = Event.objects.all().order_by('event_date')
    today = date.today()
    current_day = today.strftime("%A")

    return render(
        request,
        'reminderapp/all_events.html',
        context={
            'events': events,
            'today': today,
            'current_day': current_day,
        }
    )


@login_required
def event_detail_view(request, event_id):

    event = Event.objects.get(id=event_id)

    name = event.event_name
    planned = event.event_date
    planned_at_time = event.event_time
    remind_on = event.reminder_date
    remind_at = event.reminder_time

    return render(
        request,
        'reminderapp/event_detail.html',
        context={
            'name': name,
            'planned': planned,
            'remind_on': remind_on,
            'remind_at': remind_at,
            'planned_at_time': planned_at_time,
        }
    )


@login_required
def event_update_view(request, event_id):

    event = Event.objects.get(id=event_id)
    user = request.user

    if request.method == "GET":

        name = event.event_name
        planned = event.event_date
        planned_at_time = event.event_time
        remind_on = event.reminder_date
        remind_at = event.reminder_time

        return render(
            request,
            'reminderapp/update_event.html',
            context={
                'name': name,
                'planned': planned,
                'planned_at_time': planned_at_time,
                'remind_on': remind_on,
                'remind_at': remind_at,
            }
        )

    if request.method == "POST":

        new_event = request.POST.get('event')
        new_date = request.POST.get('date')
        new_time = request.POST.get('event_time')
        new_reminder_date = request.POST.get('reminder_date')
        new_reminder_time = request.POST.get('reminder_time')
        check = request.POST.get('check')


        if new_event:
            event.event_name = new_event
            event.save()

        if new_date:
            event.event_date = new_date
            event.save()

        if new_time:
            event.event_time = new_time
            event.save()

        if new_reminder_date:
            event.reminder_date = new_reminder_date
            event.save()

        if new_reminder_time:
            event.reminder_time = new_reminder_time
            event.save()


        dynamic_task_id = datetime.now()

        hour = int(event.reminder_time[0:2])
        minute = int(event.reminder_time[3:5])
        day = int(event.reminder_date[8:10])
        month = int(event.reminder_date[5:7])

        user_id = user.id

        schedule, created = CrontabSchedule.objects.get_or_create(hour=hour, minute=minute, day_of_month=day,
                                                                  month_of_year=month,
                                                                  timezone='Europe/Warsaw')
        task = PeriodicTask.objects.create(crontab=schedule, name=f"schedule_reminder_mail_task_{dynamic_task_id}",
                                           task='reminderapp.tasks.send_reminder_mail_func', one_off=True,
                                           args=json.dumps(([event_id, user_id])))

        if check:
            task_two = PeriodicTask.objects.create(crontab=schedule,
                                                   name=f"schedule_reminder_sms_task_{dynamic_task_id}",
                                                   task='reminderapp.tasks.send_reminder_sms_func', one_off=True,
                                                   args=json.dumps(([event_id, user_id])))

        name = event.event_name
        planned = event.event_date
        planned_at_time = event.event_time
        remind_on = event.reminder_date
        remind_at = event.reminder_time

        return render(
            request,
            'reminderapp/event_detail.html',
            context={
                'name': name,
                'planned': planned,
                'planned_at_time': planned_at_time,
                'remind_on': remind_on,
                'remind_at': remind_at,

            }
        )



@login_required
def event_delete_view(request, event_id):

    event = Event.objects.get(id=event_id)

    if request.method == "GET":
        return render(
            request,
            'reminderapp/delete_event.html',
            context={
                'event': event,
            }
        )

    if request.method == "POST":

        event.delete()
        return redirect('reminderapp:all-events-view')

reminderapp/templates/reminderapp/add_event.html
{% extends 'homepageapp/base_2.html' %}

{% load static %}
{% load tz %}

{% block content %}

    <div class="container-fluid page-header">
        <div class="container">

<div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Reminder on your events</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>
    <h3>Add new event:</h3>
    <form method="POST">{% csrf_token %}
        <input type="text" name="event">
        <input type="submit" value="Add">
    </form>
            <br>
    <a href="{% url 'reminderapp:all-events-view' %}"><button type="button" class="btn btn-info">Back</button></a>


        </div>
    </div>

{% endblock %}

reminderapp/templates/reminderapp/all_events.html
{% extends 'homepageapp/base_2.html' %}
{% load static %}
{% load tz %}

{% block content %}

    <div class="container-fluid page-header">
        <div class="container">

<div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Reminder on your events</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>

    <p><a href="{% url 'reminderapp:add-event-view' %}"><button class="btn btn-success">Add event</button></a></p>

        <h3 style="color:dimgrey;">Your planned events:</h3>

        {% for event in events %}
        {% if user.username == event.user or user.is_staff %}

        <div style="background:#e6e6fa !important" class="jumbotron">
                <h3><a href="{% url 'reminderapp:event-detail-view' event.id %}">{{ event.event_name }}</a></h3>
                <p><h4 style="color:dimgrey;">Planned for: {{ event.event_date }}</h4></p>
                <p><h5 style="color:dimgrey;">Scheduled at: {{ event.event_time }}</h5></p>
                <a href="{% url 'reminderapp:event-update-view' event.id %}"><button>Update</button></a>
                <a href="{% url 'reminderapp:event-delete-view' event.id %}"><button>Delete</button></a>
        </div>
        {% endif %}
        {% endfor %}



{% endblock %}

reminderapp/templates/reminderapp/delete_event.html
{% extends 'homepageapp/base_2.html' %}
{% load static %}
{% load tz %}

{% block content %}
<div class="container-fluid page-header">
<div class="container">

    <div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Reminder on your events</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>


    <h3 style="color:dimgrey;">Do you want to delete this event: {{ event.event_name }}?</h3>
    <br>

  <form method="POST">{% csrf_token %}
    <p><input type="submit" value="Confirm" class="btn btn-info">
  </form>
  <a href="{% url 'reminderapp:all-events-view' %}"><button class="btn btn-info">Back</button></a></p>

</div>
</div>


{% endblock %}

reminderapp/templates/reminderapp/event_detail.html
{% extends 'homepageapp/base_2.html' %}
{% load static %}
{% load tz %}

{% block content %}

<div class="container-fluid page-header">
<div class="container">

<div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Reminder on your events</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>


        <h3>Event: {{ name }}</h3>
        <p>Planned for: {{ planned }}</p>
        <p>Planned at: {{ planned_at_time }}</p>
        <p>Remind me on: {{ remind_on }}</p>
        <p>Remind me at: {{ remind_at }}</p>


    <a href="{% url 'reminderapp:all-events-view' %}"><button class="btn btn-info">Back</button></a>

</div>
</div>

{% endblock %}

reminderapp/templates/reminderapp/update_event.html
{% extends 'homepageapp/base_2.html' %}
{% load static %}
{% load tz %}

{% block content %}

    <div class="container-fluid page-header">
        <div class="container">

<div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Reminder on your events</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>

 <h3>Update this event: {{ event.id }}</h3>
    <form method="POST">{% csrf_token %}
        <h3>{{ name }}</h3>
        <br>
        <p>Event date: {{ planned }}</p>
        <input type="date" name="date">
        <br>
        <br>
        <p>Event time: {{ planned_at_time }}</p>
        <input type="time" name="event_time">
        <br>
        <br>
        <p>Remind me on: {{ remind_on }}</p>
        <input type="date" name="reminder_date">
        <br>
        <br>
        <p>Remind me at this time: {{ remind_at }}</p>
        <input type="time" name="reminder_time">

        <br>
        <br>
        <h5>Do you want to get SMS reminder as well? <input type="checkbox" name="check"></h5>

        <br>

        <p><input type="submit" value="Update" class="btn btn-info"></p>
        </form>
        <a href="{% url 'reminderapp:all-events-view' %}"><button class="btn btn-info">Back</button></a>


        {{ hour }}
        <br>
        {{ minute }}

     </div>
    </div>

{% endblock %}