EquiTimeProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepageapp.urls')),
    path('', include('scheduleapp.urls')),
    path('', include('noticeboardapp.urls')),
    path('', include('reminderapp.urls')),
    path('', include('competitionapp.urls')),
]

competitionapp/urls.py
from django.urls import path
from . import views

app_name = 'competitionapp'

urlpatterns = [
    # R
    path("current-competitions-in-Poland/", views.current_competitions_view, name="current-competitions-view")

]

homepageapp/urls.py
from django.urls import path
from . import views

app_name = 'homepageapp'

urlpatterns = [
    path('', views.home_view, name='home-view'),
    path('register/', views.register_view, name='register-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('signin/', views.login_view, name='login-view'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('index/', views.index_view, name='index-view'),

]

noticeboardapp/urls.py
from django.urls import path

from . import views

app_name = 'noticeboardapp'

urlpatterns = [
    # C
    path('add-notice/', views.add_notice_view, name='add-notice-view'),

    # R
    path('noticeboard/', views.noticeboard_view, name='noticeboard-view'),

    # U
    path('<str:notice_title>/<int:notice_id>/update/', views.update_notice_view, name='update-notice-view'),

    # D
    path('<str:notice_title>/<int:notice_id>/delete/', views.delete_notice_view, name='delete-notice-view'),
    path('delete-notices/', views.delete_all_notices, name='delete-all-notices'),

]

reminderapp/urls.py
from django.urls import path
from . import views

app_name = 'reminderapp'

urlpatterns = [

    # C
    path('add-event/', views.add_event_view, name='add-event-view'),

    # R
    path('events/', views.all_events_view, name='all-events-view'),
    path('<int:event_id>/event/', views.event_detail_view, name='event-detail-view'),

    # U
    path('<int:event_id>/event/update/', views.event_update_view, name='event-update-view'),

    # D
    path('<int:event_id>/event/delete/', views.event_delete_view, name='event-delete-view'),

    ]

scheduleapp/urls.py
from django.urls import path

from . import views

app_name = 'scheduleapp'

urlpatterns = [

    # C
    path('add/', views.schedule_create_view, name='schedule-create-view'),

    # R
    path('schedule/', views.schedule_full_view, name='schedule-full-view'),
    path('<int:activity_id>/', views.activity_detail_view, name='activity-detail-view'),

    # U
    path('<int:activity_id>/update/', views.activity_update_view, name='activity-update-view'),

    # D
    path('<int:activity_id>/delete/', views.activity_delete_view, name='activity-delete-view'),

    path('monday/', views.monday_view, name='monday-view'),

    path('tuesday/', views.tuesday_view, name='tuesday-view'),

    path('wednesday/', views.wednesday_view, name='wednesday-view'),

    path('thursday/', views.thursday_view, name='thursday-view'),

    path('friday/', views.friday_view, name='friday-view'),

    path('saturday/', views.saturday_view, name='saturday-view'),

    path('sunday/', views.sunday_view, name='sunday-view'),

    path('refresh/', views.delete_all_activities, name='delete-all-activities'),

]

scheduleapp/models.py
from django.db import models


# Create your models here.
class Activity(models.Model):

    content = models.CharField(max_length=500)
    week_day = models.CharField(max_length=25)
    user = models.CharField(max_length=50, default='Guest')

scheduleapp/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from scheduleapp.models import Activity
from django.http import JsonResponse
from datetime import date, datetime
from django.contrib.auth.decorators import login_required




# Create your views here.


@login_required
def schedule_create_view(request):

    if request.method == "GET":
        return render(
            request,
            'scheduleapp/add.html'
        )

    if request.method == "POST":

        activity = request.POST.get('activity')
        current_user = request.user

        if activity:
            Activity.objects.create(content=activity, user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/full_schedule.html'
        )


@login_required
def schedule_full_view(request):

    monday_activities = Activity.objects.filter(week_day='monday')
    tuesday_activities = Activity.objects.filter(week_day='tuesday')
    weds_activities = Activity.objects.filter(week_day='wednesday')
    thursday_activities = Activity.objects.filter(week_day='thursday')
    friday_activities = Activity.objects.filter(week_day='friday')
    saturday_activities = Activity.objects.filter(week_day='saturday')
    sunday_activities = Activity.objects.filter(week_day='sunday')
    today = date.today()
    current_day = today.strftime("%A")


    if request.user.is_authenticated:

        return render(
            request,
            'scheduleapp/full_schedule.html',
            context={
                'monday_activities': monday_activities,
                'tuesday_activities': tuesday_activities,
                'weds_activities': weds_activities,
                'thursday_activities': thursday_activities,
                'friday_activities': friday_activities,
                'saturday_activities': saturday_activities,
                'sunday_activities': sunday_activities,
                'today': today,
                'current_day': current_day,

            }
        )

    else:
        return redirect('homepageapp:login-view')


@login_required
def activity_detail_view(request, activity_id):

    activity = Activity.objects.get(id=activity_id)

    return render(
        request,
        'scheduleapp/activity.html',
        context={
            'activity': activity,
        }
    )


@login_required
def activity_update_view(request, activity_id):

    activity = Activity.objects.get(id=activity_id)

    if request.method == "GET":
        return render(
            request,
            'scheduleapp/update_activity.html',
            context={
                'activity': activity,
            }
        )

    if request.method == "POST":
        new_activity = request.POST.get('activity')

        if new_activity:
            activity.content = new_activity
            activity.save()

        return redirect('scheduleapp:schedule-full-view')



@login_required
def activity_delete_view(request, activity_id):

    activity = Activity.objects.get(id=activity_id)


    if request.method == "GET":
        return render(
            request,
            'scheduleapp/delete_activity.html',
            context={
                'activity': activity,
            }
        )

    if request.method == "POST":
        activity.delete()
        return redirect('scheduleapp:schedule-full-view')




@login_required
def monday_view(request):

    if request.method == "POST":

        monday_activity = request.POST.get('monday')
        current_user = request.user

        if monday_activity:
            Activity.objects.create(content=monday_activity, week_day='monday', user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/monday.html')

    if request.method == "GET":

        monday_activities = Activity.objects.filter(week_day='monday')

        return render(
            request,
            'scheduleapp/monday.html',
            context={
                'monday_activities': monday_activities
            }
        )


@login_required
def tuesday_view(request):

    if request.method == "POST":

        tuesday_activity = request.POST.get('tuesday')
        current_user = request.user

        if tuesday_activity:
            Activity.objects.create(content=tuesday_activity, week_day='tuesday', user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/tuesday.html')

    if request.method == "GET":

        tuesday_activities = Activity.objects.filter(week_day='tuesday')

        return render(
            request,
            'scheduleapp/tuesday.html',
            context={
                'tuesday_activities': tuesday_activities,
            }
        )


@login_required
def wednesday_view(request):

    if request.method == "POST":

        weds_activity = request.POST.get('wednesday')
        current_user = request.user

        if weds_activity:
            Activity.objects.create(content=weds_activity, week_day='wednesday', user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/wednesday.html')

    if request.method == "GET":

        weds_activities = Activity.objects.filter(week_day='wednesday')

        return render(
            request,
            'scheduleapp/wednesday.html',
            context={
                'weds_activities': weds_activities,
            }
        )


@login_required
def thursday_view(request):

    if request.method == "POST":

        thursday_activity = request.POST.get('thursday')
        current_user = request.user

        if thursday_activity:
            Activity.objects.create(content=thursday_activity, week_day='thursday', user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/thursday.html')

    if request.method == "GET":

        thursday_activities = Activity.objects.filter(week_day='thursday')

        return render(
            request,
            'scheduleapp/thursday.html',
            context={
                'thursday_activities': thursday_activities,
            }
        )


@login_required
def friday_view(request):

    if request.method == "POST":

        friday_activity = request.POST.get('friday')
        current_user = request.user

        if friday_activity:
            Activity.objects.create(content=friday_activity, week_day='friday', user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/friday.html')

    if request.method == "GET":

        friday_activities = Activity.objects.filter(week_day='friday')

        return render(
            request,
            'scheduleapp/friday.html',
            context={
                'friday_activities': friday_activities,
            }
        )


@login_required
def saturday_view(request):

    if request.method == "POST":

        saturday_activity = request.POST.get('saturday')
        current_user = request.user

        if saturday_activity:
            Activity.objects.create(content=saturday_activity, week_day='saturday', user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/saturday.html')

    if request.method == "GET":

        saturday_activities = Activity.objects.filter(week_day='saturday')

        return render(
            request,
            'scheduleapp/saturday.html',
            context={
                'saturday_activities': saturday_activities,
            }
        )


@login_required
def sunday_view(request):

    if request.method == "POST":

        sunday_activity = request.POST.get('sunday')
        current_user = request.user

        if sunday_activity:
            Activity.objects.create(content=sunday_activity, week_day='sunday', user=current_user)

            return redirect('scheduleapp:schedule-full-view')

        return render(
            request,
            'scheduleapp/sunday.html')

    if request.method == "GET":

        sunday_activities = Activity.objects.filter(week_day='sunday')

        return render(
            request,
            'scheduleapp/sunday.html',
            context={
                'sunday_activities': sunday_activities,
            }
        )


@login_required
def delete_all_activities(request):

    activities = Activity.objects.all()

    if request.method == "POST":
        if activities and request.user.is_staff:
            activities.delete()

            return redirect('scheduleapp:schedule-full-view')

        else:
            return render(
                request,
                'scheduleapp/no_permission.html'
            )


    if request.method == "GET":
        return render(
            request,
            'scheduleapp/delete_all.html',
        )


@login_required
def current_date_view(request):

    current_date = datetime.now()
    current_day = current_date.strftime("%A")

    if request.method == "GET":

        return render(
            request,
            'scheduleapp/full_schedule.html',
            context={
                'current_date': current_date,
                'current_day': current_day,
            }
        )

scheduleapp/templates/scheduleapp/activity.html
{% extends 'homepageapp/base.html' %}

{% block content %}

  <h3>Activity:</h3>
      <p>{{ activity.content }}</p>
      <p>Added by: {{ activity.user }}</p>
        <br>
        <a href="{% url 'scheduleapp:activity-update-view' activity.id %}"><button class="btn btn-info">Update</button></a>
        <a href="{% url 'scheduleapp:activity-delete-view' activity.id %}"><button class="btn btn-info">Delete</button></a>
        <a href="{% url 'scheduleapp:schedule-full-view' %}"><button class="btn btn-info">Back</button ></a>


{% endblock %}

scheduleapp/templates/scheduleapp/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Add new activity:</h3>

    <form method="post">{% csrf_token %}
        {% if user.is_authenticated %}
        <input type="text" name="activity">
        <input type="submit" value="Dodaj">
        {% endif %}

    </form>

</body>
</html>

scheduleapp/templates/scheduleapp/delete_activity.html
{% extends 'homepageapp/base.html' %}
{% load static %}

{% block content %}

    <h3>Do you want to delete this activity?</h3>
    {{ activity.content }}
    <br>
    <br>
    <form method="POST">{% csrf_token %}
        {% if user.username == activity.user or user.is_staff %}
        <p><input type="submit" value="Confirm" class="btn btn-info"></p>
        {% else %}
        <p>You can only delete your activities!</p>
        {% endif %}
    </form>

  <a href="{% url 'scheduleapp:schedule-full-view' %}"><button class="btn btn-info">Back</button></a>

{% endblock %}

scheduleapp/templates/scheduleapp/delete_all.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Do you really want to clear the schedule?</h3>
    <h4 style="color:red;">It cannot be undone...</h4>

    <form method="post">{% csrf_token %}
    <p><input type="submit" value="Confirm" class="btn btn-info"></p>
    </form>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>


{% endblock %}

scheduleapp/templates/scheduleapp/friday.html
{% extends 'homepageapp/base.html' %}

{% block content %}

<h3>Friday</h3>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>
    <h4>Add activity:</h4>

    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <input type="text" name="friday" placeholder="horse-activity-hour">
        <input type="submit" value="Add" class="btn btn-info">
    </form>
    {% endif %}

    <h4>All activities planned for Friday:</h4>
    <ol>
    {% for activity in friday_activities %}
        <li>{{ activity.content }}, added by: {{activity.user }}</li>
    {% endfor %}
     </ol>

{% endblock %}

scheduleapp/templates/scheduleapp/full_schedule.html
{% load static %}
{% load tz %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>EquiTime Schedule</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
    <p class="navbar-text">You are logged in as: {{ user }}</p>
    <a href="{% url 'homepageapp:home-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Home</button></a>
    <a href="{% url 'homepageapp:logout-view' %}"><button type="button" style="margin-right:10px; margin-top:7px;" class="btn btn-primary pull-right">Log out</button></a>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Schedule</button>
    <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Noticeboard</button></a>
    <a href="{% url 'reminderapp:all-events-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Reminder</button></a>
    <a href="{% url 'competitionapp:current-competitions-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Competitions</button></a>


    </nav>

    <div class="container-fluid page-header">
        <div class="container">

<div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Schedule for current week</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>



    <div class="container">
    <div class="row seven-cols">
    <div class="col-md-1">
      <h3><a href="{% url 'scheduleapp:monday-view' %}"><button class="btn btn-primary btn-block">Monday</button></a></h3>
        <h5><a href="{% url 'scheduleapp:monday-view' %}"><button class="btn btn-success btn-block">Add activity</button></a></h5>
      {% for activity in monday_activities %}
            <p><a href="{% url 'scheduleapp:activity-detail-view' activity.id %}">{{ activity.content }}</a></p>
    {% endfor %}
    </div>
    <div class="col-md-1">
      <h3><a href="{% url 'scheduleapp:tuesday-view' %}"><button class="btn btn-primary btn-block">Tuesday</button></a></h3>
        <h5><a href="{% url 'scheduleapp:tuesday-view' %}"><button class="btn btn-success btn-block">Add activity</button></a></h5>
      {% for activity in tuesday_activities %}
            <p><a href="{% url 'scheduleapp:activity-detail-view' activity.id %}">{{ activity.content }}</a></p>
    {% endfor %}
    </div>
    <div class="col-md-1">
      <h3><a href="{% url 'scheduleapp:wednesday-view' %}"><button class="btn btn-primary btn-block">Wednesday</button></a></h3>
        <h4><a href="{% url 'scheduleapp:wednesday-view' %}"><button class="btn btn-success btn-block">Add activity</button></a></h4>
      {% for activity in weds_activities %}
            <p><a href="{% url 'scheduleapp:activity-detail-view' activity.id %}">{{ activity.content }}</a></p>
    {% endfor %}
    </div>
        <div class="col-md-1">
      <h3><a href="{% url 'scheduleapp:thursday-view' %}"><button class="btn btn-primary btn-block">Thursday</button></a></h3>
        <h4><a href="{% url 'scheduleapp:thursday-view' %}"><button class="btn btn-success btn-block">Add activity</button></a></h4>
      {% for activity in thursday_activities %}
            <p><a href="{% url 'scheduleapp:activity-detail-view' activity.id %}">{{ activity.content }}</a></p>
    {% endfor %}
    </div>
        <div class="col-md-1">
      <h3><a href="{% url 'scheduleapp:friday-view' %}"><button class="btn btn-primary btn-block">Friday</button></a></h3>
        <h4><a href="{% url 'scheduleapp:friday-view' %}"><button class="btn btn-success btn-block">Add activity</button></a></h4>
      {% for activity in friday_activities %}
            <p><a href="{% url 'scheduleapp:activity-detail-view' activity.id %}">{{ activity.content }}</a></p>
    {% endfor %}
    </div>
        <div class="col-md-1">
      <h3><a href="{% url 'scheduleapp:saturday-view' %}"><button class="btn btn-primary btn-block">Saturday</button></a></h3>
        <h4><a href="{% url 'scheduleapp:saturday-view' %}"><button class="btn btn-success btn-block">Add activity</button></a></h4>
      {% for activity in saturday_activities %}
            <p><a href="{% url 'scheduleapp:activity-detail-view' activity.id %}">{{ activity.content }}</a></p>
    {% endfor %}
    </div>
        <div class="col-md-1">
      <h3><a href="{% url 'scheduleapp:sunday-view' %}"><button class="btn btn-primary btn-block">Sunday</button></a></h3>
        <h4><a href="{% url 'scheduleapp:sunday-view' %}"><button class="btn btn-success btn-block">Add activity</button></a></h4>
      {% for activity in sunday_activities %}
            <p><a href="{% url 'scheduleapp:activity-detail-view' activity.id %}">{{ activity.content }}</a></p>
    {% endfor %}
    </div>
    </div>

    <br>
        <br>

    <a href="{% url 'scheduleapp:delete-all-activities' %}"><button type="button" class="btn btn-info">Clear schedule</button></a>
        </div>

        <br>
        <br>
        </div>
    </div>


</body>
</html>

scheduleapp/templates/scheduleapp/monday.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Monday</h3>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>
    <h4>Add activity:</h4>
    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <input type="text" name="monday" placeholder="horse-activity-hour">
        <input type="submit" value="Add" class="btn btn-info">
    </form>
    {% endif %}

    <h4>All activities planned for Monday:</h4>
    <ol>
    {% for activity in monday_activities %}
        <li>{{ activity.content }}, added by: {{activity.user }}</li>
    {% endfor %}
        </ol>

{% endblock %}

scheduleapp/templates/scheduleapp/no_permission.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h4 style="color:red;">No permission...</h4>
    <h4>Only the administrator can clear the schedule.</h4>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>


{% endblock %}

scheduleapp/templates/scheduleapp/saturday.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Saturday</h3>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>
    <h4>Add activity:</h4>
    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <input type="text" name="saturday" placeholder="horse-activity-hour">
        <input type="submit" value="Add" class="btn btn-info">
    </form>
    {% endif %}

    <h4>All activities planned for Saturday:</h4>
    <ol>
    {% for activity in saturday_activities %}
        <li>{{ activity.content }}, added by: {{activity.user }}</li>
    {% endfor %}
        </ol>

{% endblock %}

scheduleapp/templates/scheduleapp/sunday.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Sunday</h3>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>
    <h4>Add activity:</h4>
    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <input type="text" name="sunday" placeholder="horse-activity-hour">
        <input type="submit" value="Add" class="btn btn-info">
    </form>
    {% endif %}

    <h4>All activities planned for Sunday:</h4>
    <ol>
    {% for activity in sunday_activities %}
        <li>{{ activity.content }}, added by: {{activity.user }}</li>
    {% endfor %}
        </ol>

{% endblock %}

scheduleapp/templates/scheduleapp/thursday.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Thursday</h3>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>
    <h4>Add activity:</h4>

    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <input type="text" name="thursday" placeholder="horse-activity-hour">
        <input type="submit" value="Add" class="btn btn-info">
    </form>
    {% endif %}


    <h4>All activities planned for Thursday:</h4>
    <ol>
    {% for activity in thursday_activities %}
        <li>{{ activity.content }}, added by: {{activity.user }}</li>
    {% endfor %}
        </ol>

{% endblock %}

scheduleapp/templates/scheduleapp/tuesday.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Tuesday</h3>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>
    <h4>Add activity:</h4>

    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <input type="text" name="tuesday" placeholder="horse-activity-hour">
        <input type="submit" value="Add" class="btn btn-info">
    </form>
    {% endif %}


    <h4>All activities planned for Tuesday:</h4>
    <ol>
    {% for activity in tuesday_activities %}
        <li>{{ activity.content }}, added by: {{activity.user }}</li>
    {% endfor %}
        </ol>

{% endblock %}

scheduleapp/templates/scheduleapp/update_activity.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Update this activity</h3>
    <form method="POST">{% csrf_token %}
        <input type="text" name="activity" value="{{ activity.content }}">

        {% if user.username == activity.user or user.is_staff %}
        <input type="submit" value="Update" class="btn btn-info">
        {% else %}
        <p>You can only update your activities!</p>
        {% endif %}
    </form>
   <a href="{% url 'scheduleapp:schedule-full-view' %}"><button class="btn btn-info">Back</button></a>


{% endblock %}

scheduleapp/templates/scheduleapp/wednesday.html
{% extends 'homepageapp/base.html' %}

{% block content %}

    <h3>Wednesday</h3>
    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info">Back</button></a>
    <h4>Add activity:</h4>

    {% if user.is_authenticated %}
    <form method="post">{% csrf_token %}
        <input type="text" name="wednesday" placeholder="horse-activity-hour">
        <input type="submit" value="Add" class="btn btn-info">
    </form>
    {% endif %}

    <h4>All activities planned for Wednesday:</h4>
    <ol>
    {% for activity in weds_activities %}
        <li>{{ activity.content }}, added by: {{activity.user }}</li>
    {% endfor %}
        </ol>


{% endblock %}