EquiTimeProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepageapp.urls')),
    path('', include('scheduleapp.urls')),
    path('', include('noticeboardapp.urls')),
    path('', include('reminderapp.urls')),
    path('', include('competitionapp.urls')),
]

competitionapp/urls.py
from django.urls import path
from . import views

app_name = 'competitionapp'

urlpatterns = [
    # R
    path("current-competitions-in-Poland/", views.current_competitions_view, name="current-competitions-view")

]

homepageapp/urls.py
from django.urls import path
from . import views

app_name = 'homepageapp'

urlpatterns = [
    path('', views.home_view, name='home-view'),
    path('register/', views.register_view, name='register-view'),
    path('logout/', views.logout_view, name='logout-view'),
    path('signin/', views.login_view, name='login-view'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('index/', views.index_view, name='index-view'),

]

noticeboardapp/urls.py
from django.urls import path

from . import views

app_name = 'noticeboardapp'

urlpatterns = [
    # C
    path('add-notice/', views.add_notice_view, name='add-notice-view'),

    # R
    path('noticeboard/', views.noticeboard_view, name='noticeboard-view'),

    # U
    path('<str:notice_title>/<int:notice_id>/update/', views.update_notice_view, name='update-notice-view'),

    # D
    path('<str:notice_title>/<int:notice_id>/delete/', views.delete_notice_view, name='delete-notice-view'),
    path('delete-notices/', views.delete_all_notices, name='delete-all-notices'),

]

reminderapp/urls.py
from django.urls import path
from . import views

app_name = 'reminderapp'

urlpatterns = [

    # C
    path('add-event/', views.add_event_view, name='add-event-view'),

    # R
    path('events/', views.all_events_view, name='all-events-view'),
    path('<int:event_id>/event/', views.event_detail_view, name='event-detail-view'),

    # U
    path('<int:event_id>/event/update/', views.event_update_view, name='event-update-view'),

    # D
    path('<int:event_id>/event/delete/', views.event_delete_view, name='event-delete-view'),

    ]

scheduleapp/urls.py
from django.urls import path

from . import views

app_name = 'scheduleapp'

urlpatterns = [

    # C
    path('add/', views.schedule_create_view, name='schedule-create-view'),

    # R
    path('schedule/', views.schedule_full_view, name='schedule-full-view'),
    path('<int:activity_id>/', views.activity_detail_view, name='activity-detail-view'),

    # U
    path('<int:activity_id>/update/', views.activity_update_view, name='activity-update-view'),

    # D
    path('<int:activity_id>/delete/', views.activity_delete_view, name='activity-delete-view'),

    path('monday/', views.monday_view, name='monday-view'),

    path('tuesday/', views.tuesday_view, name='tuesday-view'),

    path('wednesday/', views.wednesday_view, name='wednesday-view'),

    path('thursday/', views.thursday_view, name='thursday-view'),

    path('friday/', views.friday_view, name='friday-view'),

    path('saturday/', views.saturday_view, name='saturday-view'),

    path('sunday/', views.sunday_view, name='sunday-view'),

    path('refresh/', views.delete_all_activities, name='delete-all-activities'),

]

homepageapp/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class PhoneModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number format: '+999999999'. Up to 15 digits allowed.")
    phone_number = PhoneNumberField(validators=[phone_regex], blank=True, null=True)


    def __str__(self):
        return f"{self.phone_number}"

homepageapp/views.py
from datetime import date
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from EquiTimeProject import settings
from .models import PhoneModel
from .tokens import generate_token
import phonenumbers

# Create your views here.

def home_view(request):
    today = date.today()
    current_day = today.strftime("%A")


    return render(
        request,
        'homepageapp/home.html',
        context={
            'today': today,
            'current_day': current_day,
        }
    )


def register_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        pass1 = request.POST.get('pass1')
        pass2 = request.POST.get('pass2')

        if User.objects.filter(username=username) and User.is_active:
            messages.error(request, 'Username already exists. Please try some other username.')
            return redirect('homepageapp:register-view')

        # if User.objects.filter(email=email):
        #     messages.error(request, 'Email already registered. Please use another email address.')
        #     return redirect('homepageapp:register-view')

        if len(username) > 10:
            messages.error(request, 'Username must be under 10 characters.')
            return redirect('homepageapp:register-view')

        if pass1 != pass2:
            messages.error(request, "Passwords didn't match.")
            return redirect('homepageapp:register-view')

        if not username.isalnum():
            messages.error(request, "Username must be Alpha-Numeric.")
            return redirect('homepageapp:register-view')

        my_user = User.objects.create_user(username, email, pass1)
        my_user.first_name = fname
        my_user.last_name = lname
        my_user.is_active = False
        my_user.save()

        phone_number = request.POST.get('phone_number')

        phone_number = PhoneModel(phone_number=phone_number, user=my_user)
        if phonenumbers.is_valid_number(phone_number.phone_number):
            phone_number.save()
        else:
            messages.error(request, "This is not a valid phone number. Please give your number with country code "
                                    "and without any spaces, e.g. +48111222333")
            my_user.delete()
            return redirect('homepageapp:register-view')

        messages.success(request, "Your account has been successfully created. "
                                  "We have sent you welcome and address confirmation emails!")

        # Welcome Email

        subject = "Welcome to EquiTime Application!"
        message = 'Hello ' + my_user.first_name + "! \n" + "Thank you for visiting our website. \n" \
                                                           "Your login: " + my_user.username
        from_email = settings.EMAIL_HOST_USER
        to_list = [my_user.email]
        # fail_silently=True / if our email fails to send it still won't crash our app
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        # Email with confirmation link

        current_site = get_current_site(request)
        email_title = "Confirm your email address."
        message_2 = render_to_string('email_confirmation.html', {
            'name': my_user.first_name,
            'username': my_user.username,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(my_user.pk)),
            'token': generate_token.make_token(my_user),
        })
        email = EmailMessage(
            email_title,
            message_2,
            settings.EMAIL_HOST_USER,
            [my_user.email],
        )
        email.fail_silently = True
        email.send()

        return redirect('homepageapp:index-view')

    if request.method == "GET":
        return render(
            request,
            'registration/register.html',
        )


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        my_user = User.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        my_user = None

    if my_user is not None and generate_token.check_token(my_user, token):
        my_user.is_active = True
        my_user.save()
        login(request, my_user)
        return render(
            request,
            'email_confirmed.html',
        )
    else:
        return render(
            request,
            'activation_failed.html'
        )


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        pass1 = request.POST['pass1']

        my_user = authenticate(request, username=username, password=pass1)

        if my_user is not None:
            login(request, my_user)
            fname = my_user.first_name
            return render(
                request,
                'homepageapp/home.html',
                context={
                    'fname': fname
                }
            )

        else:
            messages.error(request, "Bad credentials! Please make sure that you confirmed your email address.")

            return redirect('homepageapp:index-view')

    if request.method == "GET":
        return render(
            request,
            'registration/signin.html'
        )


def index_view(request):
    return render(
        request,
        'registration/index.html',
    )


def logout_view(request):
    logout(request)
    messages.success(request, "You are logged out!")
    # return redirect('homepageapp:home-view')

    return render(
        request,
        'registration/logout.html',
    )

homepageapp/templates/homepageapp/base.html
{% load static %}
{% load tz %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>EquiTime</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <a href="{% url 'homepageapp:home-view' %}"><button type="button" style="margin-left:5px; margin-top:7px;" class="btn btn-primary">Home</button></a>
        {% if user.is_authenticated %}
        <p class="navbar-text">You are logged in as: {{ user }}</p>
        <a href="{% url 'homepageapp:logout-view' %}"><button type="button" style="margin-right:10px; margin-top:7px;" class="btn btn-primary pull-right">Log out</button></a>
        {% else %}
        <a href="{% url 'homepageapp:login-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Log in</button></a>
        <a href="{% url 'homepageapp:register-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Sign up</button></a>
        {% endif %}
        <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Schedule</button></a>
        <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Noticeboard</button></a>
        <a href="{% url 'reminderapp:all-events-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Reminder</button></a>
        <a href="{% url 'competitionapp:current-competitions-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Competitions</button></a>



    </nav>

    <div class="container-fluid page-header">
        <div class="container">

    <div style="background:#e6e6fa !important" class="jumbotron text-center">
    <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Welcome to EquiTime App</h1>
    <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
    <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
    </div>


    {% block content %}

    {% endblock %}
            </div>

</div>

<img src="{% static 'img/lila_horse.jpg' %}" alt="My image">

</body>
</html>

homepageapp/templates/homepageapp/base_2.html
{% load static %}
{% load tz %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>EquiTime</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <a href="{% url 'homepageapp:home-view' %}"><button type="button" style="margin-left:5px; margin-top:7px;" class="btn btn-primary">Home</button></a>
        {% if user.is_authenticated %}
        <p class="navbar-text">You are logged in as: {{ user }}</p>
        <a href="{% url 'homepageapp:logout-view' %}"><button type="button" style="margin-right:10px; margin-top:7px;" class="btn btn-primary pull-right">Log out</button></a>
        {% else %}
        <a href="{% url 'homepageapp:login-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Log in</button></a>
        <a href="{% url 'homepageapp:register-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Sign up</button></a>
        {% endif %}
        <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Schedule</button></a>
        <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Noticeboard</button></a>
        <a href="{% url 'reminderapp:all-events-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Reminder</button></a>
        <a href="{% url 'competitionapp:current-competitions-view' %}"><button type="button" style="margin-top:7px;" class="btn btn-primary">Competitions</button></a>


    </nav>

    {% block content %}

    <div class="container-fluid page-header">
            <div class="container">

        <div style="background:#e6e6fa !important" class="jumbotron text-center">
        <h1 style="color:dimgrey; font-family: Lucida Handwriting, cursive;">Welcome to EquiTime App</h1>
        <p style="font-size:250%; color:dimgrey;">{{ today }}</p>
        <p style="font-size:200%; color:dimgrey;">{{ current_day }}<p>
        </div>

        </div>
    </div>
    {% endblock %}

<img src="{% static 'img/lila_horse.jpg' %}" alt="My image">

</body>
</html>

homepageapp/templates/homepageapp/home.html
{% extends 'homepageapp/base.html' %}
{% load static %}


{% block content %}

    <a href="{% url 'scheduleapp:schedule-full-view' %}"><button type="button" class="btn btn-info btn-lg btn-block">Schedule</button>
    <br>
    <a href="{% url 'noticeboardapp:noticeboard-view' %}"><button type="button" class="btn btn-info btn-lg btn-block">Noticeboard</button>
    <br>
    <a href="{% url 'reminderapp:all-events-view' %}"><button type="button" class="btn btn-info btn-lg btn-block">Reminder</button>
    <br>
    <a href="{% url 'competitionapp:current-competitions-view' %}"><button type="button" class="btn btn-info btn-lg btn-block">Current competitions in Poland</button>



{% endblock %}